export const JOURNAL_FEED_LOADED = "JOURNAL_FEED_LOADED"
export const SINGLE_JOURNAL_LOADED = "SINGLE_JOURNAL_LOADED"
export const SWITCH_JOURNAL_TAB = "SWITCH_JOURNAL_TAB"
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM"
